apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-nfs-pvc
  labels:
    app: vllm
  namespace: vllm
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: crobasaurusrex-nfs
  resources:
    requests:
      storage: 256Gi
