apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-nfs-pvc
  labels:
    app: open-webui
  namespace: open-webui
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: crobasaurusrex-nfs
  resources:
    requests:
      storage: 2Gi
