# This should create:
# Single pod gitea deployment
# 1 gitea actions runner per node in the cluster (can restrict with nodeselectors/taints), deployed automagically

namespace: gitea

ingress:
  enabled: false

deployment:
  nodeSelector: crobasaurusrex # Deploy on crobasaurusrex as it has more disk space.

# There is a typo in this (persistEnce) so k3s autoprovisioned storage on the host disk. We'll need to fix that sometime.
# note that postgres storage in gitea is also provisioned this way.
persistance:
  enabled: true
  claimName: gitea-pvc

# Single pod configuration, disable HA options for Redis and Postgres
redis-cluster:
  enabled: false
redis:
  enabled: true
postgresql:
  enabled: true
  # Auto upgrade from Postgres 16 to 17 using the pgautoupgrade image & bitnami helm chart
  primary:
    initContainers: 
      - name: upgrade-postgres
        image: pgautoupgrade/pgautoupgrade:17-bookworm
        securityContext:
          runAsUser: 0
        volumeMounts:
          - mountPath: /bitnami/postgresql
            name: data
        env:
          - name: PGAUTO_ONESHOT
            value: "yes"
          - name: POSTGRES_DB
            value: gitea
          - name: PGDATA
            value: /bitnami/postgresql/data
          # The value for POSTGRES_PASSWORD does not really matter, as it's never used in one-shot mode.        
          - name: POSTGRES_PASSWORD
            value: password

postgresql-ha:
  enabled: false

gitea:
  admin:
    existingSecret: gitea-admin-secret
  config:
    database:
      DB_TYPE: postgres
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true



