# This should create:
# Single pod gitea deployment
# 1 gitea actions runner per node in the cluster (can restrict with nodeselectors/taints), deployed automagically

namespace: gitea

ingress:
  enabled: false

deployment:
  nodeSelector: crobasaurusrex # Deploy on crobasaurusrex as it has more disk space.

# There is a typo in this (persistEnce) so k3s autoprovisioned storage on the host disk. We'll need to fix that sometime.
# note that postgres storage in gitea is also provisioned this way.
persistance:
  enabled: true
  claimName: gitea-pvc

# Single pod configuration, disable HA options for Redis and Postgres
redis-cluster:
  enabled: false
redis:
  enabled: true
postgresql:
  enabled: true
postgresql-ha:
  enabled: false

gitea:
  admin:
    existingSecret: gitea-admin-secret
  config:
    database:
      DB_TYPE: postgres
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true