apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piper-nfs-pvc
  labels:
    app: piper
  namespace: piper
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: crobasaurusrex-nfs
  resources:
    requests:
      storage: 2Gi
