apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: crobasaurusrex-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: nfs-server.nfs-server.svc.cluster.local
  share: /
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1