apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: simpleapps.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: SimpleApp
    spec:
      image: string
      port: integer | default=80
      hostnames: "[]string"
  resources:
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.metadata.name}
          namespace: ${schema.metadata.namespace}
        spec:
          selector:
            matchLabels:
              app: ${schema.metadata.name}
          template:
            metadata:
              labels:
                app: ${schema.metadata.name}
            spec:
              containers:
                - name: app
                  image: ${schema.spec.image}
                  ports:
                    - containerPort: ${schema.spec.port}
                      name: http
    - id: service
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: ${schema.metadata.name}
          namespace: ${schema.metadata.namespace}
        spec:
          selector:
            app: ${schema.metadata.name}
          ports:
            - port: ${schema.spec.port}
              targetPort: http
              protocol: TCP
              name: http
    - id: httproute
      template:
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: ${schema.metadata.name}
          namespace: ${schema.metadata.namespace}
        spec:
          parentRefs:
            - group: gateway.networking.k8s.io
              kind: Gateway
              name: crobceratops-gateway
              namespace: gateways
            - group: gateway.networking.k8s.io
              kind: Gateway
              name: crobasaurusrex-gateway
              namespace: gateways
          hostnames: ${schema.spec.hostnames}
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: /
              backendRefs:
                - group: ""
                  kind: Service
                  name: ${schema.metadata.name}
                  port: ${schema.spec.port}
