apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec: # https://github.com/crossplane-contrib/provider-aws/releases
  package: xpkg.upbound.io/crossplane-contrib/provider-aws:v0.54.2