apiVersion: batch/v1
kind: CronJob
metadata:
  name: s3-sync-ryanbeales-com
  namespace: ryanbeales-com
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sync
              image: amazon/aws-cli:latest
              command:
                - /bin/sh
                - -c
                - |
                  echo "Installing git..."
                  yum install -y git

                  echo "Setting up SSH..."
                  mkdir -p ~/.ssh
                  cp /etc/github-deploy-key/ssh-privatekey ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan github.com >> ~/.ssh/known_hosts

                  echo "Cloning repo..."
                  git clone git@github.com:ryanbeales/wwwryanbealescom.git /tmp/repo

                  echo "Syncing to S3..."
                  aws s3 sync /tmp/repo s3://www.ryanbeales.com --delete --exclude ".git/*"
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: s3-sync-creds
                      key: username
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: s3-sync-creds
                      key: password
                - name: AWS_DEFAULT_REGION
                  value: eu-west-2
              volumeMounts:
                - name: github-deploy-key
                  mountPath: "/etc/github-deploy-key"
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: github-deploy-key
              secret:
                secretName: github-deploy-key
