apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: s3-syncer-policy-ryanbeales-com
  namespace: ryanbeales-com
spec:
  forProvider:
    description: "Policy for S3 syncing of ryanbeales.com"
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "s3:PutObject",
              "s3:DeleteObject",
              "s3:ListBucket",
              "s3:GetObject"
            ],
            "Resource": [
              "arn:aws:s3:::www.ryanbeales.com",
              "arn:aws:s3:::www.ryanbeales.com/*"
            ]
          }
        ]
      }
  providerConfigRef:
    name: upbound-aws-default
