apiVersion: v1
kind: ConfigMap
metadata:
  name: password-reset-script
  namespace: photoprism-melissa
data:
  resetpassword.sql.tmpl: | 
    CREATE USER IF NOT EXISTS root@localhost IDENTIFIED BY '${MARIADB_ROOT_PASSWORD}';
    SET PASSWORD FOR root@localhost = PASSWORD('${MARIADB_ROOT_PASSWORD}');
    GRANT ALL ON *.* TO root@localhost WITH GRANT OPTION;
    CREATE USER IF NOT EXISTS root@'%' IDENTIFIED BY '${MARIADB_ROOT_PASSWORD}';
    SET PASSWORD FOR root@'%' = PASSWORD('${MARIADB_ROOT_PASSWORD}');
    GRANT ALL ON *.* TO root@'%' WITH GRANT OPTION;
    CREATE USER IF NOT EXISTS ${MARIADB_USER}@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';
    SET PASSWORD FOR ${MARIADB_USER}@'%' = PASSWORD('${MARIADB_PASSWORD}');
    CREATE DATABASE IF NOT EXISTS ${MARIADB_DATABASE};
    GRANT ALL ON ${MARIADB_DATABASE}.* TO ${MARIADB_USER}@'%';  
  passwordreset.sh: |
    #!/bin/sh
    apt update
    apt install -y gettext 
    envsubst < /var/lib/passwordreset/resetpassword.sql.tmpl > /resetpassword.sql
    runuser -l mysql -c '/usr/bin/nohup /usr/sbin/mariadbd --init-file=/resetpassword.sql &'
    sleep 120
    killall -s SIGTERM mariadbd