apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-db-pvc
  labels:
    app: photoprism
  namespace: photoprism-melissa
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage-zfs
  volumeName: photoprism-melissa-db-pv
  resources:
    requests:
      storage: 2000Gi
