apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: duplicati-config-storage-claim
  labels:
    app: duplicati
  namespace: duplicati
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage-zfs
  volumeName: duplicati-config-pv
  resources:
    requests:
      storage: 256Mi
