namespace: duplicati
resources:
- duplicati-namespace.yaml
- duplicati-pv.yaml
- duplicati-pvc.yaml
- duplicati-config-pv.yaml
- duplicati-config-pvc.yaml
helmCharts:
  - name: duplicati
    includeCRDs: true
    valuesFile: values.yaml
    releaseName: duplicati
    version: 5.3.1
    repo: https://k8s-at-home.com/charts/