resources:
- dns/croblociraptor-direct.yaml
- dns/croblociraptor-wildcard.yaml
- dns/crobasaurusrex-direct.yaml
- dns/crobasaurusrex-wildcard.yaml
- dns/crobceretops-direct.yaml
- dns/crobceretops-wildcard.yaml
- dns/aws-acm-validation.yaml
- dns/blog.ryanbeales.com.yaml
- dns/blog.ryanbeales.com-validation.yaml
- dns/www.ryanbeales.com.yaml