apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
  labels:
    app: vaultwarden
  namespace: vaultwarden
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage-zfs
  volumeName: vaultwarden-pv
  resources:
    requests:
      storage: 1Gi
