apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octoprint-pvc
  labels:
    app: octoprint
  namespace: octoprint
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage-zfs
  volumeName: octoprint-pv
  resources:
    requests:
      storage: 1Gi
