apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-config
  namespace: filebrowser
  labels:
    app.kubernetes.io/name: filebrowser
data:
  config.yaml: |
    server:
      port: 80
      baseURL: "/"
      logging:
        - levels: "info|warning|error"
      sources:
        - path: "/srv"
    auth:
      methods:
        password:
          enabled: true
          minLength: 5
          signup: false
        passkey:
          enabled: false
