apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-nfs-pvc
  namespace: filebrowser
  labels:
    app.kubernetes.io/name: filebrowser
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: crobasaurusrex-nfs
  resources:
    requests:
      storage: 10Gi
