# New local stroage provisioer, uses the ranger local-path provisioner to create directories on the host node automagically.
# You must also update the local-path-config ConfigMap to include the new path. It is in the kube-system namespace, add
# the path to the DEFAULT_PATH_FOR_NON_LISTED_NODES variable.
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: auto-local-storage-zfs
provisioner: rancher.io/local-path
parameters:
  nodePath: /stash
volumeBindingMode: WaitForFirstConsumer