apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea-act-runner
  namespace: gitea
spec:
  template:
    spec:
      volumes:
      - name: docker-socket
        emptyDir: {}
      containers:
      - name: act-runner
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/user/1000/
      - name: dind
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/user/1000/