apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea
helmCharts:
- name: gitea
  repo: 'oci://registry-1.docker.io/giteacharts/'
  version: 10.6.0 # https://gitea.com/gitea/helm-chart/releases
  releaseName: gitea
  namespace: gitea
  valuesFile: values.yaml
  includeCRDs: true
resources:
- gitea-pvc.yaml
- gitea-pv.yaml
# Version 10.6.0 of the chart doesn't support adding extra volumes in to the actions runner set.
# So we do that here with a kustomize patch, we can remove this after updating from 10.6.0 since
# https://gitea.com/gitea/helm-chart/commit/1d908965a8dbb3dd33fa078b4cd4a74d3dc2cfe2 has been merged.
patches:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: gitea-act-runner
  path: act-runner-patch.yaml