# This should create:
# Single pod gitea deployment
# 1 gitea actions runner per node in the cluster (can restrict with nodeselectors/taints), deployed automagically

namespace: gitea

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
    cert-manager.io/cluster-issuer: letsencryptcertmanager
  hosts:
    - host: gitea.crobasaurusrex.ryanbeales.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: gitea-crobasaurusrex-ryanbeales-com-tls
      hosts:
        - gitea.crobasaurusrex.ryanbeales.com

deployment:
  nodeSelector: crobasaurusrex # Deploy on crobasaurusrex as it has more disk space.

# There is a typo in this (persistEnce) so k3s autoprovisioned storage on the host disk. We'll need to fix that sometime.
# note that postgres storage in gitea is also provisioned this way.
persistance:
  enabled: true
  claimName: gitea-pvc


# Provision gitea-actions statefulset, we should end up with 2 runners.
actions:
  enabled: true
  provisioning:
    enabled: true
  statefulset:
    actRunner:
      tag: 0.2.11-dind-rootless
      # By default, the helm chart does not populate the labels section of the runner config.
      # This means all jobs start in a bare image without the necessary tools.
      config: |
        log:
          level: debug
        cache:
          enabled: false
        runner:
          labels:
            - "ubuntu-latest:docker://gitea/runner-images:ubuntu-latest"
            - "ubuntu-22.04:docker://gitea/runner-images:ubuntu-22.04"
            - "ubuntu-20.04:docker://gitea/runner-images:ubuntu-20.04"
        container:
          # Force the runner to mount the dind containers docker socket to allow for docker in docker.
          # Set the DOCKER_HOST to use the mounted socket.
          options: "-v /var/run/user/1000/docker.sock:/dockersock/docker.sock:ro -e DOCKER_HOST=unix:///dockersock/docker.sock"
          # The above option will fail if the docker socket directory is not listed in valid volumes. Time lost here: 4 hours.
          # It's wildcarded for now but should be locked down to the one path above. but It's working right now and I don't want
          # to mess it up.
          valid_volumes:
            - '**'
    dind:
      tag: 25.0.2-dind-rootless

# Single pod configuration, disable HA options for Redis and Postgres
redis-cluster:
  enabled: false
redis:
  enabled: true
postgresql:
  enabled: true
postgresql-ha:
  enabled: false

gitea:
  admin:
    existingSecret: gitea-admin-secret
  config:
    database:
      DB_TYPE: postgres
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true