apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-deep-research-data-nfs-pvc
  labels:
    app: local-deep-research
  namespace: local-deep-research
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: crobasaurusrex-nfs
  resources:
    requests:
      storage: 2Gi
