apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: mqtt
    app.kubernetes.io/name: mosquitto
  name: mosquitto
  namespace: mosquitto
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mosquitto
      app.kubernetes.io/name: mosquitto
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mosquitto
        app.kubernetes.io/name: mosquitto
    spec:
      containers:
        # https://hub.docker.com/_/eclipse-mosquitto/tags
        - image: eclipse-mosquitto:1.6.15
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 1883
            timeoutSeconds: 1
          name: mosquitto
          ports:
            - containerPort: 1883
              name: mqtt
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 1883
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /mosquitto/config
              name: config-volume
            - mountPath: /mosquitto/data/
              name: mosquitto-data
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: mosquitto
          name: config-volume
        - emptyDir: {}
          name: mosquitto-data