apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mosquitto
helmCharts:
- name: mosquitto
  repo: 'https://naps.github.io/helm-charts/'
  version: 1.0.4
  releaseName: mosquitto
  namespace: mosquitto
  valuesFile: values.yaml
  includeCRDs: true
resources:
- ./namespace.yaml