apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  ports:
    - name: mqtt
      port: 1883
      protocol: TCP
      targetPort: mqtt
  selector:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
  type: ClusterIP