apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: crobasaurusrex-gateway
  namespace: gateways
  annotations:
    cert-manager.io/cluster-issuer: letsencryptcertmanager
spec:
  gatewayClassName: envoy-gateway
  listeners:
    - name: https
      protocol: HTTPS
      port: 444
      hostname: "*.crobasaurusrex.ryanbeales.com"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: crobasaurusrex-ryanbeales-com-tls
            kind: Secret