apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway-system
helmCharts:
- name: gateway-helm
  repo: oci://docker.io/envoyproxy/
  version: v1.5.0
  releaseName: envoy-gateway
  namespace: envoy-gateway-system
  valuesFile: values.yaml
  includeCRDs: true
resources:
- ./namespace.yaml
patches:
# Server side apply this one since it's very large.
- target:
     kind: CustomResourceDefinition
     name: envoyproxies.gateway.envoyproxy.io
  patch: |
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-options: ServerSideApply=true
        