apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway-system
helmCharts:
- name: envoy-gateway
  repo: oci://docker.io/envoyproxy/gateway-helm
  version: v2.0.4
  releaseName: envoy-gateway
  namespace: envoy-gateway-system
  includeCRDs: true
resources:
- ./namespace.yaml