apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-nfs-pvc
  labels:
    app: ollama
  namespace: ollama
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: crobasaurusrex-nfs
  resources:
    requests:
      storage: 256Gi
