# Use an alternative image in the postgres chart for now. I'll migrate out once it's all generated and up.
# Immich instructions are here https://immich.app/docs/administration/postgres-standalone/

image:
  # Use pgvector-rs image which has the vectors.so library loaded already
  registry: ghcr.io
  repository: immich-app/postgres # https://github.com/immich-app/base-images/pkgs/container/postgres
  tag: 16-vectorchord0.3.0-pgvectors0.2.0

auth:
  existingSecret: immich-postgres-secrets
  username: immich
  database: immich

# Helm chart will override the list of shared libraries so vectors needs to be added back in here
postgresqlSharedPreloadLibraries: "vectors.so,pgaudit"

primary:
  networkPolicy:
    enabled: false
  # No node affinity or nodeselector since the PVC is doing that for us.
  persistence:
    existingClaim: immich-postgres-pvc
  # For pgvector-rs
  containerSecurityContext:
    readOnlyRootFilesystem: false
  initdb:
    scripts:
      create-extensions.sql: |
        CREATE EXTENSION IF NOT EXISTS cube;
        CREATE EXTENSION IF NOT EXISTS earthdistance;
        CREATE EXTENSION IF NOT EXISTS vectors;
  resources:
    limits:
      cpu: 1