# Use an alternative image in the postgres chart for now. I'll migrate out once it's all generated and up.
image:
  repository: tensorchord/pgvecto-rs # https://hub.docker.com/r/tensorchord/pgvecto-rs/tags
  tag: pg16-v0.3.0

auth:
  existingSecret: immich-postgres-secrets
  username: immich
  database: immich

primary:
  networkPolicy:
    enabled: false
  # No node affinity or nodeselector since the PVC is doing that for us.
  persistence:
    existingClaim: immich-postgres-pvc
  # For pgvector-rs
  containerSecurityContext:
    readOnlyRootFilesystem: false
  initdb:
    scripts:
      create-extensions.sql: |
        CREATE EXTENSION cube;
        CREATE EXTENSION earthdistance;
        CREATE EXTENSION vectors;
  livenessProbe:
    initialDelaySeconds: 300
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 10
  readinessProbe:
    initialDelaySeconds: 300
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 10