global:
  security:
     allowInsecureImages: true # This is so we can use the pgvecto-rs image below without the giant security warning from the chart.

image:
  repository: tensorchord/pgvecto-rs # https://hub.docker.com/r/tensorchord/pgvecto-rs/tags
  tag: pg16-v0.3.0

auth:
  existingSecret: immich-postgres-secrets
  username: immich
  database: immich

primary:
  networkPolicy:
    enabled: false
  # No node affinity or nodeselector since the PVC is doing that for us.
  persistence:
    existingClaim: immich-postgres-pvc
  initdb:
    scripts:
      create-extensions.sql: |
        CREATE EXTENSION cube;
        CREATE EXTENSION earthdistance;
        CREATE EXTENSION vectors;