apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dia
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: gitea.crobasaurusrex.ryanbeales.com/ryanbeales/dia
  newTag: latest