apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache-pvc
  labels:
    app: chromaimagegen
  namespace: chromaimagegen
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: auto-local-storage-zfs
  resources:
    requests:
      storage: 256Mi # Ignorded.
