apiVersion: v1
kind: ConfigMap
metadata:
  name: biqu-b1-printerprofile
  namespace: octoprint
data:
  printer.profile: |
    axes:
      e:
        inverted: false
        speed: 300
      x:
        inverted: false
        speed: 6000
      y:
        inverted: false
        speed: 6000
      z:
        inverted: false
        speed: 200
    color: default
    extruder:
      count: 1
      defaultExtrusionLength: 5
      nozzleDiameter: 0.4
      offsets:
      - - 0.0
        - 0.0
      sharedNozzle: false
    heatedBed: true
    heatedChamber: false
    id: _default
    model: Biqu B1
    name: Biqu B1
    volume:
      custom_box: false
      depth: 235.0
      formFactor: rectangular
      height: 270.0
      origin: lowerleft
      width: 235.0