apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: birdnet-data-nfs-pvc
  namespace: birdnet
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: crobasaurusrex-nfs
  resources:
    requests:
      storage: 4Gi
