apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
helmCharts:
- name: ingress-nginx
  # https://github.com/kubernetes/ingress-nginx?tab=readme-ov-file#supported-versions-table
  repo: 'https://kubernetes.github.io/ingress-nginx'
  version: v4.13.0
  releaseName: ingress-nginx
  namespace: ingress-nginx
  valuesFile: values.yaml
  includeCRDs: true
resources:
- ./namespace.yaml