controller:
  ingressClassResource:
    default: true

  # This is for backwards compatibility with the ingress class annotation.
  ingressClass: "nginx"

  labels:
    ingress-nginx-controller-name: "default-origin-ingress-nginx"

  replicaCount: 1

  resources:
    requests:
       cpu: "250m"
       memory: "90Mi"

  service:
    enableHttp: false

  nodeSelector:
    kubernetes.io/hostname: crobasaurusrex

  config:
    # Allow up to Critical risk level annotations as we control the ingress objects - eg: this isn't a shared platform.
    annotations-risk-level: "Critical" # Fix for vaultwarden websocket config