apiVersion: v1
kind: PersistentVolume
metadata:
  name: kopia-config-pv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-zfs
  local:
    path: /butter/kopia
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - crobasaurusrex
