apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kopia-config-storage-claim
  namespace: kopia
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage-zfs
  volumeName: kopia-config-pv
  resources:
    requests:
      storage: 256Mi
