apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media-nfs-claim
  labels:
    app: frigate
  namespace: frigate
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: crobasaurusrex-nfs
  resources:
    requests:
      storage: 512Gi
