apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config-claim
  labels:
    app: frigate
  namespace: frigate
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage-zfs
  volumeName: frigate-config-pv
  resources:
    requests:
      storage: 128Mi
