apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frigate
helmCharts:
- name: frigate
  repo: 'https://blakeblackshear.github.io/blakeshome-charts/'
  version: 7.5.1
  releaseName: frigate
  namespace: frigate
  valuesFile: values.yaml
  includeCRDs: true
resources:
- ./namespace.yaml
- ./frigate-config-pv.yaml
- ./frigate-config-pvc.yaml
- ./frigate-media-pv.yaml
- ./frigate-media-pvc.yaml

