# see https://artifacthub.io/packages/helm/blakeblackshear/frigate for hints...

config: |
  mqtt:
    host: mosquitto.mosquitto.svc.cluster.local
    port: 1883
    user: admin
    password: admin
  birdseye:
    enabled: True
    mode: continuous
  go2rtc:
    streams:
      back:
        - http://10.0.0.153/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_REOCAM_PASSWORD}
      back_sub:
        - ffmpeg:http://10.0.0.153/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password={FRIGATE_REOCAM_PASSWORD}
      front:
        - rtsp://admin:{FRIGATE_ARMCREST_FRONT_PASSWORD}@10.0.0.67/cam/realmonitor?channel=1&subtype=0
      front_sub:
        - rtsp://admin:{FRIGATE_ARMCREST_FRONT_PASSWORD}@10.0.0.67/cam/realmonitor?channel=1&subtype=1
  # Available hardware accellerated codecs:
  #  V..... av1_cuvid            Nvidia CUVID AV1 decoder (codec av1)
  #  V..... h264_cuvid           Nvidia CUVID H264 decoder (codec h264)
  #  V..... hevc_cuvid           Nvidia CUVID HEVC decoder (codec hevc)
  #  V..... mjpeg_cuvid          Nvidia CUVID MJPEG decoder (codec mjpeg)
  #  V..... mpeg1_cuvid          Nvidia CUVID MPEG1VIDEO decoder (codec mpeg1video)
  #  V..... mpeg2_cuvid          Nvidia CUVID MPEG2VIDEO decoder (codec mpeg2video)
  #  V..... mpeg4_cuvid          Nvidia CUVID MPEG4 decoder (codec mpeg4)
  #  V..... vc1_cuvid            Nvidia CUVID VC1 decoder (codec vc1)
  #  V..... vp8_cuvid            Nvidia CUVID VP8 decoder (codec vp8)
  #  V..... vp9_cuvid            Nvidia CUVID VP9 decoder (codec vp9)
  cameras:
    back:
      ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/back?video=copy&audio=aac
            input_args: preset-rtsp-restream
            roles:
              - audio
              - record
          - path: rtsp://127.0.0.1:8554/back_sub?video=copy
            input_args: preset-rtsp-restream
            roles:
              - detect
        hwaccel_args: preset-nvidia-h264
        output_args:
          record: preset-record-generic-audio-aac
      snapshots:
        enabled: true
        required_zones:
          - yard
      motion:
        mask:
          - 0.998,0.671,0.999,0.998,0,0.998,0.003,0.467,0.174,0.421,0.251,0.341,0.267,0.22,0.61,0.229,0.673,0.384,0.676,0.217,0.71,0.218
      zones:
        yard:
          coordinates: 0.998,0.671,0.999,0.998,0,0.998,0.003,0.467,0.174,0.421,0.251,0.341,0.267,0.22,0.61,0.229,0.673,0.384,0.676,0.217,0.71,0.218
      birdseye:
        order: 2
      genai:
        enabled: True
        use_snapshot: True
    front:
      ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/front?video=copy&audio=aac
            input_args: preset-rtsp-restream
            roles:
              - audio
              - record
          - path: rtsp://127.0.0.1:8554/front_sub?video=copy
            input_args: preset-rtsp-restream
            roles:
              - detect
        hwaccel_args: preset-nvidia-h264
        output_args:
          record: preset-record-generic-audio-aac
      snapshots:
        enabled: true
        required_zones:
          - driveway
      motion:
        mask:
          - 0.339,0.816,0.408,1,0.614,1,1,1,1,0.577,1,0.356,0.696,0.269,0.53,0.473,0.393,0.392,0.367,0.279,0.246,0.161,0.004,0.403,0,0.487,0.004,0.675,0.137,0.525,0.193,0.616,0.214,0.665,0.278,0.704,0.307,0.725
      zones:
        driveway:
          coordinates: 0.339,0.816,0.408,1,0.614,1,1,1,1,0.577,1,0.356,0.696,0.269,0.53,0.473,0.393,0.392,0.367,0.279,0.246,0.161,0.004,0.403,0,0.487,0.004,0.675,0.137,0.525,0.193,0.616,0.214,0.665,0.278,0.704,0.307,0.725
      # Stop detecting people that arent in the masked area, like the statue which keeps triggering detections...
      review:
        alerts:
          required_zones:
            - driveway
        detections:
          required_zones:
            - driveway
      birdseye:
        order: 1
      genai:
        enabled: True
        use_snapshot: True
  detectors:
    tensorrt:
      type: tensorrt
      device: 0
  # https://docs.frigate.video/configuration/object_detectors/#generate-models
  model:
    path: /config/model_cache/tensorrt/yolov7-640.trt
    input_tensor: nchw
    input_pixel_format: rgb
    width: 640
    height: 640
  record:
    enabled: true
    retain:
      days: 7
      mode: all
    alerts:
      retain:
        days: 7
        mode: active_objects
    detections:
      retain:
        days: 30
        mode: active_objects
  objects:
    track:
      - person
      - cat
      - dog
      - bird
      - bear
      - bicycle
      - horse
      - sheep
      - cow
      - elephant
      - shoe
      - skis
  audio:
    enabled: true
    listen:
      - bark
      - fire_alarm
      - scream
      - speech
      - yell
  semantic_search:
    enabled: True
    reindex: False
    model_size: large
  genai:
    enabled: true
    provider: ollama
    base_url: http://ollama.ollama.svc.cluster.local:11434
    model: gemma3:4b-it-qat

env:
  TZ: America/Vancouver
  YOLO_MODELS: yolov7-640


envFromSecrets:
  - reocam-password
  - armcrest-front-password

image:
  # https://github.com/blakeblackshear/frigate/releases
  tag: "0.15.0-tensorrt"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencryptcertmanager
  hosts:
    - host: frigate.crobasaurusrex.ryanbeales.com
      paths:
        - "/"
  tls:
    - secretName: frigate-crobasaurusrex-ryanbeales-com-tls
      hosts: 
        - frigate.crobasaurusrex.ryanbeales.com

gpu:
  nvidia:
    enabled: true
    runtimeClassName: nvidia

persistence:
  config:
    enabled: true
    existingClaim: frigate-config-claim
  media:
    enabled: true
    existingClaim: frigate-media-claim

probes:
  startup:
    enabled: true