apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: personal-projects
resources:
- namespace.yaml
- deployment.yaml
images:
- name: gitea.crobasaurusrex.ryanbeales.com/ryanbeales/build-test
  newTag: 92263c3