ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencryptcertmanager
  hosts:
    - jupyter.crobasaurusrex.ryanbeales.com
  tls:
    - secretName: jupyter-crobasaurusrex-ryanbeales-com-tls
      hosts:
        - jupyter.crobasaurusrex.ryanbeales.com

hub:
  config:
    Authenticator:
      admin_users:
        - ryanbeales
      allowed_users:
        - ryanbeales
    KubeSpawner:
      extra_pod_config:
        runtimeClassName: nvidia
    JupyterHub:
      admin_access: true

singleuser:
  networkPolicy:
    enabled: false # disable network policy
  profileList:
    - display_name: "GPU Server"
      description: "Spawns a notebook server with access to a GPU"
      kubespawner_override:
        extra_resource_limits:
          nvidia.com/gpu: "1"
        node_selector: 
          kubernetes.io/hostname: crobceratops
  storage:
    dynamic:
      storageClass: auto-local-storage-zfs # store on k3s node for now.
    capacity: 2Gi