apiVersion: cloudfront.aws.upbound.io/v1beta1
kind: Function
metadata:
  name: ryanbeales-redirect-to-www
  labels:
    function: ryanbeales-redirect-to-www
spec:
  forProvider:
    region: us-east-1
    runtime: cloudfront-js-1.0
    comment: Redirect apex domain to www subdomain
    code: |
      function handler(event) {
        var request = event.request;
        var host = request.headers.host.value;
        
        if (host === 'ryanbeales.com') {
          return {
            statusCode: 301,
            statusDescription: 'Moved Permanently',
            headers: {
              'location': { value: 'https://www.ryanbeales.com' + request.uri }
            }
          };
        }
        
        return request;
      }
  providerConfigRef:
    name: upbound-aws-default
