apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-notebook-notebook-nfs-pvc
  labels:
    app: open-notebook
  namespace: open-notebook
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: crobasaurusrex-nfs
  resources:
    requests:
      storage: 2Gi
