apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-ryan-db-pv
  namespace: photoprism
spec:
  capacity:
    storage: 7000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-zfs
  local:
    path: /stash/photoprism-db-ryan
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - crobasaurusrex
