apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoprism
  namespace: photoprism-ryan
spec:
  selector:
    matchLabels:
      app: photoprism
  replicas: 1
  template:
    metadata:
      labels:
        app: photoprism
    spec:
      nodeSelector:
        kubernetes.io/hostname: crobasaurusrex
      containers:
      - name: photoprism
        image: photoprism/photoprism:240711
        env:
        - name: PHOTOPRISM_DEBUG
          value: "false"
        - name: PHOTOPRISM_CACHE_PATH
          value: /assets/cache
        - name: PHOTOPRISM_IMPORT_PATH
          value: /assets/photos/import
        - name: PHOTOPRISM_EXPORT_PATH
          value: /assets/photos/export
        - name: PHOTOPRISM_ORIGINALS_PATH
          value: /assets/photos/originals
        - name: PHOTOPRISM_DATABASE_DRIVER
          value: mysql
        - name: PHOTOPRISM_HTTP_HOST
          value: 0.0.0.0
        - name: PHOTOPRISM_HTTP_PORT
          value: "2342"
        - name: PHOTOPRISM_SPONSOR
          value: "true"
        # Load database DSN & admin password from secret
        envFrom:
        - secretRef:
            name: photoprism-secrets
            optional: false
        ports:
        - containerPort: 2342
          name: http
        volumeMounts:
        - mountPath: /assets/photos/originals
          name: photoprism-storage
          subPath: media/photos
        - mountPath: /assets/cache
          name: photoprism-storage
          subPath: cache
        - mountPath: /assets/photos/import
          name: photoprism-storage
          subPath: import
        - mountPath: /assets/photos/export
          name: photoprism-storage
          subPath: export
        livenessProbe:
          httpGet:
            path: /api/v1/status
            port: http
          failureThreshold: 5
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /api/v1/status
            port: http
          failureThreshold: 30
          periodSeconds: 10
      volumes:
      - name: photoprism-storage
        persistentVolumeClaim:
          claimName: photoprism-pvc
