apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-pvc
  labels:
    app: photoprism
  namespace: photoprism-ryan
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage-zfs
  volumeName: photoprism-ryan-pv
  resources:
    requests:
      storage: 2000Gi
