apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: build-test
    app.kubernetes.io/name: build-test
  name: build-test
  namespace: personal-projects
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: build-test
      app.kubernetes.io/name: build-test
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: build-test
        app.kubernetes.io/name: build-test
    spec:
      containers:
        - image: gitea.crobasaurusrex.ryanbeales.com/ryanbeales/build-test:latest
          imagePullPolicy: IfNotPresent
          name: python