apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: build-test
  name: build-test
  namespace: personal-projects
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: build-test
      port: 5000
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: build-test
  sessionAffinity: None
  type: ClusterIP