apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-storage-claim
  labels:
    app: esphome
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage-zfs
  volumeName: esphome-pv
  resources:
    requests:
      storage: 256Mi
