apiVersion: apps/v1
kind: Deployment
metadata:
  name: faster-whisper
  namespace: faster-whisper
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: faster-whisper
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: faster-whisper
    spec:
      containers:
      - name: faster-whisper
        # CPU only instance
        image: lscr.io/linuxserver/faster-whisper:2.4.0 # https://hub.docker.com/r/linuxserver/faster-whisper/tags
        env:
        - name: TZ
          value: America/Vancouver
        - name: WHISPER_MODEL
          value: tiny-int8
        - name: WHISPER_LANG
          value: en
        ports:
        - name: faster-whisper
          containerPort: 10300
        volumeMounts:
        - name: storage
          # Models are downloaded and stored in the root home directory
          mountPath: /config
      volumes:
      - name: storage
        hostPath:
          path: /stash/faster-whisper
          type: DirectoryOrCreate # if the directory does not exist then create it