apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: faster-whisper
  name: faster-whisper
  namespace: faster-whisper
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: faster-whisper
      port: 10300
      protocol: TCP
      targetPort: faster-whisper
  selector:
    app.kubernetes.io/name: faster-whisper
  sessionAffinity: None
  type: ClusterIP