resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- birdnet-config-pv.yaml
- birdnet-config-pvc.yaml
- birdnet-data-pv.yaml
- birdnet-data-pvc.yaml
- birdnet-data-nfs-pvc.yaml
- birdnet-config-nfs-pvc.yaml