apiVersion: batch/v1
kind: CronJob
metadata:
  name: refresher
  namespace: crobasaurusrex-admin
spec:
  # Run every 15 minutes
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          nodeName: crobasaurusrex
          hostNetwork: true # Required as we're doing an ARP scan

          containers:
          - name: refresher
            image: nicolaka/netshoot:v0.13
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh"]
            args: ["-c", "/refresher/refresher.sh"]
            volumeMounts:
            - name: refresher
              mountPath: "/refresher/"
              readOnly: true
            - name: mac-names
              mountPath: "/config"
              readOnly: true
            - name: coredns-config
              mountPath: "/coredns-config"
          volumes:
          - name: refresher
            configMap:
              name: refresher
              defaultMode: 0500
              items:
              - key: refresher.sh
                path: refresher.sh
          - name: mac-names
            configMap:
              name: mac-names
          - name: coredns-config
            persistentVolumeClaim:
              claimName: internal-dns-pvc
          restartPolicy: Never