apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwavejs-pvc
  labels:
    app: zwavejs
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage-zfs
  volumeName: zwavejs-pv
  resources:
    requests:
      storage: 256Mi
