apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: personal-k8s-applications
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: git@github.com:ryanbeales/personal-microk8s-config.git 
      revision: main
      files:
      - path: "*/argocd.yaml"
  template:
    metadata:
      name: '{{.argocd.name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: git@github.com:ryanbeales/personal-microk8s-config.git 
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ or .argocd.namespace .argocd.name }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true